### ISSUE TITLE
Explanation for code should come after

### ISSUE THREAD

**Issue by vezycash** [thewhitetulip/build-app-with-python-antitextbook#14]
# Section: Writing Style

### Original
Code that is supposed to run on the Interpreter starts with >>> like >>> not True. In this case, >>> not True is the statement and False is the output.
```
>>> not True
  False
```
## Reordered
Code that is supposed to run on the Interpreter starts with >>>
Example:
```
>>> not True
  False
```
In this case, >>> not True is the statement and False is the output.

**Comment by thewhitetulip** [comment]
Thank you!
