### ISSUE TITLE
Readability Fix

### ISSUE THREAD

**Issue by vezycash** [thewhitetulip/build-app-with-python-antitextbook#16]
Section: Introduction 2
Issue: Sentence is too long and would require multiple reads to understand.
Because of it's English like syntax, Python makes for an excellent prototyping language, any program implemented in Python has significantly less number of lines as compared to Java, but because it is a dynamically typed language, it is somewhat difficult to debug the programs written in Python or we need to be extra careful while writing them.

## Fix
Because of its English like syntax, Python makes for an excellent prototyping language**.** Any program implemented in Python has significantly less number of lines as compared to Java. But because it is a dynamically typed language, it is somewhat difficult to debug the programs written in Python. Thus, we need to be extra careful while writing them.

**Comment by thewhitetulip** [comment]
I guess that's ironical isn't it? :-D 

Thank you again :-)
