### ISSUE TITLE
Missing Print statement

### ISSUE THREAD

**Issue by vezycash** [thewhitetulip/build-app-with-python-antitextbook#18]
https://github.com/vezycash/build-app-with-python-antitextbook/blob/master/01-intro-to-python.md#using-glob

current code
```
>>> import glob
>>> files = glob.glob('*.txt')
>>> files
```
(in windows python 3.6, calling _files_ without a print statement does not display anything
Fix
>>> import glob
>>> files = glob.glob('*.txt')
>>> **print(files)**

**Comment by thewhitetulip** [comment]
I didn't know that python on windows doesn't print the value of a variable when we type it. I'll update every instance now.

**Comment by thewhitetulip** [comment]
Instead of changing each and every statement, I have added a note at the first occurrence that if the normal thing doesn't work, please use print.

Thanks for pointing this out!
