### ISSUE TITLE
Escape sequences do not depend on quote character

### ISSUE THREAD

**Issue by QuLogic** [thewhitetulip/build-app-with-python-antitextbook#2]
In `03-01-understanding-variables.md`, under String, it says that escapes like `\n\t` are affected by the use of `"` or `'`. This is incorrect as there is no difference to Python with respect to which quote character you use. The only difference is which character you can use _within_ the string without escaping.

If you do want to disable escape sequences, it requires prefixing the string with `r` and it doesn't matter which quote character is used. That is `r'this string\n\t'` or `r"this string\n\t"` both do not use the escape sequences and apply the strings literally.

**Comment by thewhitetulip** [comment]
Yes, it is incorrect. It is silly that I wrote that, I am sorry. It is fixed
