### ISSUE TITLE
Missing type Tuple

### ISSUE THREAD

**Issue by rahilwazir** [thewhitetulip/build-app-with-python-antitextbook#20]
The type Tuple is missing from the [Variables](https://github.com/thewhitetulip/build-app-with-python-antitextbook/blob/master/03-01-understanding-variables.md#list) section and also [High level data structure](https://github.com/thewhitetulip/build-app-with-python-antitextbook/blob/master/04-list-set-dict.md)?

**Comment by thewhitetulip** [comment]
I have been working on adding the text but haven't pushed it yet :-)
