### ISSUE TITLE
use .format() instead of % for string formatin (PEP3103)

### ISSUE THREAD

**Issue by STguerin** [thewhitetulip/build-app-with-python-antitextbook#27]
see [PEP3101](https://www.python.org/dev/peps/pep-3101/)  .format was introduce in python 2.6 and should be the preferred way to do string interpolation

**Comment by thewhitetulip** [comment]
You are right, I'll make the changes. Thanks for pointing it out!

**Comment by thewhitetulip** [comment]
Changes have been made! Starting form python3.6, we don't even have to use .format()

```python
i = 0
print(f"{i}")
```

This is amazing.
