### ISSUE TITLE
How do you start your books?

### ISSUE THREAD

**Issue by norbertfuhs** [thewhitetulip/build-app-with-python-antitextbook#37]
Hi,

Suraj I would like to know how you usually start your books.

Do you first write stuff into an manuscript folder on Github and then import it to Gitbooks or do you first start with an GitBook template?

**Comment by thewhitetulip** [comment]
It is not complicated.

Write your chapters in a separate .md file
Create a SUMMARY.md file which points to each chapter file.

Now this is the leanpub structure, for gitbooks, you need a "manuscript" folder and it should contain a `Book.txt` which is same as the SUMMARY.md

Hope this helps.

In case of any doubt, just download my repo, and run `rm -rf .git`  it'll delete the git history and edit all .md files to your content
