### ISSUE TITLE
Use `glob` module instead of vanilla walks

### ISSUE THREAD

**Issue by prashnts** [thewhitetulip/build-app-with-python-antitextbook#4]
`glob` in Python 3 supports a wide variety of syntax including `**/*.txt`. Being an anti-textbook, `glob` is more suitable for `01-intro-to-python.md`, in my opinion.

```python
>>> import glob
>>> glob.glob('*.txt')
['file1.txt',
 'file2.txt',
 'file3.txt',
 'file4.txt',
 'file5.txt']
```

**Comment by thewhitetulip** [comment]
Well, my point behind not using glob is that it would be difficult for someone totally new to the language to understand it, hence usage of barebone functions. I'll add this as an alternate way of doing it. Thank you for suggesting!

**Comment by prashnts** [comment]
I suppose it's more unix-ey. Though, I get the point that this does not demonstrate a lot of language features. :)

**Comment by thewhitetulip** [comment]
Yes! I have added it in the commit ef4a73856288886ab85a0c90bebdc7bc54ad8e10. I added it just as FYI, like you don't have to use `os` and that little hack to find out all the .txt files if you become experienced in Python.

Thanks for the suggestion!
